[build]
rustflags = ["-Ctarget-cpu=native", "-Cpanic=abort"]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-Ctarget-cpu=native",
    "-Cpanic=abort",
    "-C",
    "link-arg=--ld-path=/usr/bin/mold",
]

[unstable]
# build-std = ["std", "core", "alloc", "panic_abort"]
# build-std-features = ["panic_immediate_abort"]
